import { generateSingleEliminationBracket } from '../lib/tournament';
import { PlayerProfile } from '../lib/data/types';

const dummyPlayers: PlayerProfile[] = [
  {
    id: '1',
    full_name: 'Ali Iskandarli',
    email: 'ali.iskandarli@bhos.edu.az',
    major_faculty: 'Information Security',
    admission_year: 2022,
    role: 'player',
    playing_style: 'Shakehand Offensive',
    blade_equipment: 'Viscaria ALC',
    forehand_rubber: 'Dignics 09C',
    backhand_rubber: 'Tenergy 05',
    current_elo: 1650,
    matches_played: 15,
    wins: 14,
    losses: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    full_name: 'Ali Abdulov',
    email: 'ali.abdulov@bhos.edu.az',
    major_faculty: 'Computer Science',
    admission_year: 2023,
    role: 'player',
    playing_style: 'Shakehand Allround',
    blade_equipment: 'Timo Boll ALC',
    forehand_rubber: 'Hurricane 3 Neo',
    backhand_rubber: 'Rozena',
    current_elo: 1580,
    matches_played: 12,
    wins: 9,
    losses: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    full_name: 'Fateh Memmedli',
    email: 'fateh.memmedli@bhos.edu.az',
    major_faculty: 'Process Automation',
    admission_year: 2022,
    role: 'player',
    playing_style: 'Modern Defender',
    blade_equipment: 'Joo Saehyuk',
    forehand_rubber: 'Tenergy 64',
    backhand_rubber: 'Feint Long II',
    current_elo: 1520,
    matches_played: 10,
    wins: 7,
    losses: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    full_name: 'Huseyn Muradzade',
    email: 'huseyn.muradzade@bhos.edu.az',
    major_faculty: 'Chemical Engineering',
    admission_year: 2021,
    role: 'player',
    playing_style: 'Penhold Attacker',
    blade_equipment: 'Stiga Clipper Wood',
    forehand_rubber: 'Dignics 80',
    backhand_rubber: 'Fastarc G-1',
    current_elo: 1490,
    matches_played: 10,
    wins: 6,
    losses: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

const bracket = generateSingleEliminationBracket(dummyPlayers, 'tourn-bracket-test');
console.log('Bracket generated with', bracket.rounds.length, 'rounds.');
